# set this file according to https://pythonhosted.org/PyDrive/oauth.html
client_config_backend: settings
client_config:
    client_id: "<your-client-id>"
    client_secret: "<your-secret>"
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    redirect_uri: "http://localhost:8080"

# This is disabled because it does not support absolute paths
# the credentials file is saved and loaded programatically from the configs folder
# save_credentials: True
# save_credentials_backend: file
# save_credentials_file: configs/credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install
